ersion: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    networks:
      - traefik-net
    ports:
      - '3306'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=moodle
      - ALLOW_EMPTY_PASSWORD=no
#    env_file: .env
    volumes:
      - '/docker/projetos/moodle/moodle-mariadb:/bitnami'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik-net"
#        - "traefik.frontend.rule=Host:moodledev.sertao.ifrs.edu.br"
        - "traefik.port=3306"
        - "traefik.backend=moodle-mariadb"

 moodle:
    image: 'bitnami/moodle:latest'
    networks:
      - traefik-net
    env_file: .env
    volumes:
      - '/docker/projetos/moodle/moodle-data/:/bitnami'
    depends_on:
      - mariadb
#    ports:
#      - '80:80'
#      - '443:443'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:moodledev.sertao.ifrs.edu.br"
        - "traefik.port=80"
        - "traefik.backend=moodle-data"


networks:
  traefik-net:
     external: true

volumes:
  moodle-mariadb:
    driver: local
  moodle-data:
    driver: local


