version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    networks:
      - traefik-net
      - moodle-net
    ports:
      - '3306'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=moodle
      - ALLOW_EMPTY_PASSWORD=no
#    env_file: .env
    volumes:
      - '/docker/projetos/moodle/moodle-mariadb:/bitnami'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik-net"
#        - "traefik.frontend.rule=Host:mariadbdevdev.sertao.ifrs.edu.br"
        - "traefik.port=3306"
        - "traefik.backend=moodle-mariadb"

 moodle:
    image: 'bitnami/moodle:latest'
    networks:
      - traefik-net
      - moodle-net
    env_file: .env
    volumes:
      - '/docker/projetos/moodle/moodle-data/:/bitnami'
    depends_on:
      - mariadb
    ports:
      - '180:80'
      - '1443:443'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:moodledev.sertao.ifrs.edu.br"
        - "traefik.port=80"
        - "traefik.backend=moodle-data"

phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '280:80'
      - '2443:443'
#    environment:
#      - PHPMYADMIN_ALLOW_NO_PASSWORD=false
#      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
    networks:
      - traefik-net
      - moodle-net
    env_file: .env-phpmyadmin
    volumes:
      - '/docker/projetos/moodle/moodle-phpmyadmin:/bitnami'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:phpmyadmindev.sertao.ifrs.edu.br"
        - "traefik.port=80"
        - "traefik.backend=moodle-phpmyadmin"

networks:
  traefik-net:
     external: true
  moodle-net:
    driver: overlay


volumes:
  moodle-mariadb:
    driver: local
  moodle-data:
    driver: local
  moodle-phpmyadmin:
    driver: local

