
version: "3.3"

services:
  nginx:
    image: nginx:latest
    ports:
     - 8181:80
    networks:
     - traefik-net
     - default
    deploy:
      labels:
        - "traefik.backend=nginx"
        - "traefik.frontend.rule=Host:nginx.sertao.ifrs.edu.br"
        - "traefik.enable=true"
        - "traefik.port=80"
#        - "traefik.backend.loadbalancer.swarm=true"
#        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.docker.network=traefik-net"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
         constraints: [node.role == manager]
#        constraints:
#          - node.role != manager

networks:
   traefik-net:
     external: true

