  version: '3'
  services:
    traefik:
      image: traefik
      networks:
        - traefik-net
      ports:
        - "8080:80"
        - "8443:443"
        - "8090:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /docker/projetos/traefik/config:/etc/traefik
      command: traefik --web -l DEBUG --docker --docker.swarmmode --docker.watch -c /etc/traefik/traefik.toml
      deploy:
        placement:
            constraints: [node.role == manager]
      labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.sertao.ifrs.edu.br
      - traefik.port=8080
      - traefik.docker.network=traefik-net         
            
networks:
  traefik-net:
    driver: overlay
