version: '3.3'

# Antes de rodar essa stack você deve criar network com o comando abaixo:
# docker network create --driver=overlay traefik-net

services:
  traefik:
    image: traefik
    command: --api --docker --docker.swarmmode --docker.watch --docker.domain=sertao.ifrs.edu.br  --log$
    deploy:
      placement:
        constraints: [ node.role == manager ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/projetos/traefik/config/traefik.toml:/etc/traefik/traefik.toml
#      - /docker/projetos/traefik/acme/acme.json:/etc/acme/acme.json
      - /docker/projetos/traefik/certs:/etc/traefik
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.sertao.ifrs.edu.br"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    driver: overlay
    external: true
