version: '3.3'

#networks:
#  swarm_overlay:
#    external:
#      name: traefik-net

services:
  traefik:
    image: traefik
#    command: --docker --docker.swarmmode --docker.domain=${DOMAIN} --docker.watch --web DEBUG
#     command: --docker --docker.swarmmode --docker.watch  --web -l DEBUG
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=sertao.ifrs.edu.br --logLevel=DEBUG
    deploy:
      placement:
        constraints: [ node.role == manager ]
    # docker in docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # if not using docker configs
      - /docker/projetos/traefik/config:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.sertao.ifrs.edu.br"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    driver: overlay
    external: true
#    attachable: true
